### PR TITLE
Fix the incorrect information & Fud.

### PR DESCRIPTION
**Pull request by SamCoThePuggo**
I am not associated with the Zem/Halex/Whatever of kingtinos bullshit. You put miner as my alt, however he is a fully different person. Him and a few other of the skids (dennis, rus, etc) all changed their pfp and name to "copy" me for like a day and seems he hasnt changed his back. Netherite has been around since way before the summer also, and is running off of contabo VPS's - Its been going for a few months already and it does not plan to go anywhere anytime soon.

### CODE REVIEW

**Comment by iamdeka** [comment]
Hello. Thank you for taking your time to make a PR.
Netherite.io is staying on the list - they don't even have a ToS or Privacy Policy.

**Comment by SamCoThePuggo** [comment]
If it is the case of a host not having a ToS (which netherite does, not publicly listed - ill update you with the link shortly) then ive some hosts to add:
- Gapple.host (Owner - 1083790513112612906)
- Xerin.org (Owner - 844425707178033182)

**Comment by iamdeka** [comment]
> If it is the case of a host not having a ToS (which netherite does, not publicly listed - ill update you with the link shortly)
All legal documents for your business should be public.

**Comment by iamdeka** [comment]
Gapple did not release yet. I will check Xerin.org when i get the time to.

**Comment by SamCoThePuggo** [comment]
So what if its not released? It's still accepting payments.

**Comment by HPiLO** [comment]
> If it is the case of a host not having a ToS (which netherite does, not publicly listed - ill update you with the link shortly) then ive some hosts to add:
> 
> * Gapple.host (Owner - 1083790513112612906)
> * Xerin.org (Owner - 844425707178033182)

Hey, regarding Gapple not having a publicly available Terms of Service or Privacy Policy, we do however it is only available on the updated version of our website which is still being made, hopefully will be finished today or tomorrow. This will include our terms of service, privacy policy and service level agreement. Also regarding us accepting payments without these terms public, we do not currently have any existing preorders but regardless the terms will be made available within a few days at most.

**Comment by SamCoThePuggo** [comment]
yeah netherites isnt there for a few days, yet it was added. so i dont see why gapple isnt added.

**Comment by SamCoThePuggo** [comment]
i personally think this is bias.

**Comment by iamdeka** [comment]
> i personally think this is bias.

You are the owner of Netherite.io, creating an issue with the title "Fix the incorrect information & Fud".

**Comment by SamCoThePuggo** [comment]
> You are the owner of Netherite.io, creating an issue with the title "Fix the incorrect information & Fud".

This is correct. The incorrect information was about miner and the other hosts. And fud just means Fear, unknown & doubt, of which you are spreading of netherite.

**Comment by iamdeka** [comment]
> This is correct. The incorrect information was about miner and the other hosts. And fud just means Fear, unknown & doubt, of which you are spreading of netherite.

While the changes in the PR are correct, i do not have any good reason to remove Netherite.io from the list.

**Comment by SamCoThePuggo** [comment]
> i do not have any good reason to remove Netherite.io from the list.
Okay.

But you are still dodging my point about Gapple, it should definitely be added for the following reasons:
- Owner is not even the legal age to work in the country its made in (UK, Sabrina is 14. not 16.)
- No ToS
- Website is copied from the BerryByte website.

**Comment by HPiLO** [comment]
Also about your point of the "legal age to work in the UK", it is actually 13 for part-time jobs. But regardless, I am not working I am running a non registered business.

**Comment by HPiLO** [comment]
I'll be happy to push our new terms of service, privacy policy and SLA to the current version of the site now, please allow me one moment.

**Comment by SamCoThePuggo** [comment]
> Regarding the website being "copied" from BerryByte, this was from an old version of the website, we have resolved this conflict with BerryByte directly thus replaced any infringing elements of the website.

My other two points still stand, and it was still a direct copy.

> Also about your point of the "legal age to work in the UK", it is actually 13 for part-time jobs. But regardless, I am not working I am running a non registered business.

You are accepting payments via paypal, while not old enough to do this. Creating a host is also not a "part-time job". Sure you can make one while underage, but you lack the proper access to payment processors and it is also "scummy".

**Comment by SamCoThePuggo** [comment]
> I'll be happy to push our new terms of service, privacy policy and SLA to the current version of the site now, please allow me one moment.

Brilliant.

**Comment by HPiLO** [comment]
> > I'll be happy to push our new terms of service, privacy policy and SLA to the current version of the site now, please allow me one moment.
> 
> Brilliant. I do not wish to communicate with these skids in this post anymore, hence i will (attempt to) close the PR.

🙌. As a notice, you can now view our terms on the following:

https://gapple.host/terms
https://gapple.host/privacy
https://gapple.host/sla

**Comment by iamdeka** [comment]
> But you are still dodging my point about Gapple

I hope the answers HPiLO gave are sufficent.

**Comment by SamCoThePuggo** [comment]
> I hope the answers HPiLO gave are sufficent.

He/She has still dodged some of my points. However, i do not wish to communicate further on this matter as i cant be bothered 🤣

**Comment by HPiLO** [comment]
She works fine thanks.

**Comment by atqr1** [comment]
> > i personally think this is bias.
> 
> You are the owner of Netherite.io, creating an issue with the title "Fix the incorrect information & Fud".

it is in fact FUD and has negatively affected the price of Netherite's crypto token

**Comment by atqr1** [comment]
$NETHERITE is currently plummeting due to this pr
image

**Comment by blueiicey** [comment]
> $NETHERITE is currently plummeting due to this pr image

we goin to the moon with this one
pov: netherite exploded because they got exposed

**Pull request merged**
